# ref: https://ort.pyke.io/setup/linking#configure-the-path-in-the-linker-args-in-cargoconfigtoml-to-be-relative-to-the-executable

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-Wl,-rpath=$ORIGIN"]

[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-Wl,-rpath=@loader_path"]
